// <auto-generated />
using System;
using Animal_Health_System.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Animal_Health_System.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250224194503_data")]
    partial class data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("FarmId", "Name")
                        .IsUnique();

                    b.ToTable("animals");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.AnimalHealthHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("AnimalId", "MedicalRecordId")
                        .IsUnique()
                        .HasDatabaseName("Idx_AnimalHealthHistory_AnimalId_MedicalRecordId");

                    b.HasIndex("Name", "EventDate")
                        .IsUnique()
                        .HasDatabaseName("Idx_AnimalHealthHistory_Name_EventDate");

                    b.ToTable("animalHealthHistories");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "21d4f4a9-8e26-416e-9d6b-a5c7e5b170d3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ab0986af-f4ab-4ae5-a0e3-8c8950abbbc8",
                            Email = "admin@medc.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MEDC.COM",
                            NormalizedUserName = "ADMIN@MEDC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJsvZKvRwX1kU5OL/p81DshNOMampbSH2+XOkxKHXggS+UVUqAX0G5u79IAPw46bNw==",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "39595ece-dcc8-4bf7-a1dd-460d67b482da",
                            TwoFactorEnabled = false,
                            UserName = "admin@medc.com"
                        },
                        new
                        {
                            Id = "86854584-fb05-4bfa-ae19-51dc71540f59",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b29133d0-6af0-4a78-ad8e-cf30aae1fce7",
                            Email = "owner@medc.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "OWNER@MEDC.COM",
                            NormalizedUserName = "OWNER@MEDC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELkLrlrAs6K3xkEaoDh0MrJA8LLNe6xEDIuWWHypM3X9EbnLtLraa7jTn0++f3CiYw==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "74198433-d4bc-4b2c-8ea3-35995276f5e4",
                            TwoFactorEnabled = false,
                            UserName = "owner@medc.com"
                        },
                        new
                        {
                            Id = "b9ac39b7-df87-4572-a369-d1083a507b4e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0136d547-2bee-4fcd-a404-d12ac0c4b67d",
                            Email = "veterinarian@medc.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VETERINARIAN@MEDC.COM",
                            NormalizedUserName = "VETERINARIAN@MEDC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEsB60cXXkTM1sIKSKQ5g0njizTrvxuNCZ5ryde03iImtqBSpZMB4+ZIKU887DYVLQ==",
                            PhoneNumberConfirmed = false,
                            Role = 3,
                            SecurityStamp = "4810df72-eab1-423c-9054-c9577b64431a",
                            TwoFactorEnabled = false,
                            UserName = "veterinarian@medc.com"
                        },
                        new
                        {
                            Id = "bc254da1-e0eb-4818-ab6f-90e7ece2eb07",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "532909e4-bf8f-471b-ba70-ccab42c0e788",
                            Email = "farmstaff@medc.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FARMSTAFF@MEDC.COM",
                            NormalizedUserName = "FARMSTAFF@MEDC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENnoNMCF2drlzyCsgwQKlhG0o7jBuVDCqYLuR4nRC7lFMrq02B96ZfS/ntszsN0CqA==",
                            PhoneNumberConfirmed = false,
                            Role = 2,
                            SecurityStamp = "2f5a8e88-38d7-4ce4-89c6-a817a97e7b03",
                            TwoFactorEnabled = false,
                            UserName = "farmstaff@medc.com"
                        });
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<int>("FarmStaffId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VeterinarianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("FarmStaffId");

                    b.HasIndex("VeterinarianId");

                    b.HasIndex("AnimalId", "AppointmentDate")
                        .IsUnique();

                    b.HasIndex("AnimalId", "AppointmentDate", "VeterinarianId")
                        .IsUnique();

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.AppointmentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("appointmentHistories");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Birth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("BirthCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfOffspring")
                        .HasColumnType("int");

                    b.Property<int>("PregnancyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("PregnancyId");

                    b.ToTable("births");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Name", "OwnerId")
                        .IsUnique();

                    b.ToTable("farms");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.FarmHealthSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<int>("HealthyAnimals")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SickAnimals")
                        .HasColumnType("int");

                    b.Property<int>("TotalAnimals")
                        .HasColumnType("int");

                    b.Property<int>("UnderTreatment")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FarmId")
                        .IsUnique();

                    b.ToTable("farmHealthSummaries");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.FarmStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateHired")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("FarmId", "FullName")
                        .IsUnique();

                    b.ToTable("farmStaff");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Mating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<int>("FemaleAnimalId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Ispregnancyevent")
                        .HasColumnType("bit");

                    b.Property<int>("MaleAnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("FemaleAnimalId");

                    b.HasIndex("MaleAnimalId", "FemaleAnimalId", "MatingDate")
                        .IsUnique();

                    b.ToTable("matings");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.MedicalExamination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExaminationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExaminationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VeterinarianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("VeterinarianId");

                    b.HasIndex("AnimalId", "ExaminationDate")
                        .IsUnique();

                    b.ToTable("medicalExaminations");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("medicalRecords");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("medications");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FarmStaffId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("PregnancyId")
                        .HasColumnType("int");

                    b.Property<int>("RecipientType")
                        .HasColumnType("int");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.Property<int>("SenderType")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VeterinarianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("FarmStaffId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("PregnancyId");

                    b.HasIndex("VeterinarianId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "86854584-fb05-4bfa-ae19-51dc71540f59",
                            CreatedAt = new DateTime(2025, 2, 24, 19, 45, 2, 947, DateTimeKind.Utc).AddTicks(2945),
                            Email = "owner@medc.com",
                            FullName = "John Doe",
                            IsDeleted = false,
                            PhoneNumber = "123-456-7890",
                            UpdatedAt = new DateTime(2025, 2, 24, 19, 45, 2, 947, DateTimeKind.Utc).AddTicks(2952)
                        });
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Pregnancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpectedBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasComplications")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MatingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MatingId");

                    b.HasIndex("AnimalId", "MatingDate")
                        .IsUnique()
                        .HasFilter("[AnimalId] IS NOT NULL");

                    b.ToTable("pregnancies");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Vaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("vaccines");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.VaccineHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdministrationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VaccineId")
                        .HasColumnType("int");

                    b.Property<int>("VeterinarianId")
                        .HasColumnType("int");

                    b.Property<int>("medicalRecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VaccineId");

                    b.HasIndex("VeterinarianId");

                    b.HasIndex("medicalRecordId");

                    b.ToTable("vaccineHistories");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Veterinarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("veterinarians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "b9ac39b7-df87-4572-a369-d1083a507b4e",
                            CreatedAt = new DateTime(2025, 2, 24, 19, 45, 3, 13, DateTimeKind.Utc).AddTicks(2385),
                            Email = "veterinarian@medc.com",
                            FullName = "Dr. Smith",
                            IsDeleted = false,
                            PhoneNumber = "123-456-7890",
                            Specialty = "Small Animal",
                            UpdatedAt = new DateTime(2025, 2, 24, 19, 45, 3, 13, DateTimeKind.Utc).AddTicks(2392),
                            YearsOfExperience = 5,
                            salary = 50000m
                        });
                });

            modelBuilder.Entity("MedicalExaminationMedication", b =>
                {
                    b.Property<int>("MedicalExaminationsId")
                        .HasColumnType("int");

                    b.Property<int>("MedicationsId")
                        .HasColumnType("int");

                    b.HasKey("MedicalExaminationsId", "MedicationsId");

                    b.HasIndex("MedicationsId");

                    b.ToTable("MedicalExamination_Medication", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3155ed94-b4d0-4e14-ab4d-53c68d725401",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "9428f1f4-2c39-4fce-892c-85f349322fd0",
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        },
                        new
                        {
                            Id = "409901fa-62fc-4352-a873-b674d5140611",
                            Name = "Veterinarian",
                            NormalizedName = "VETERINARIAN"
                        },
                        new
                        {
                            Id = "62a9c6e3-04be-4a4c-9a4a-1aa2a32d0c66",
                            Name = "FarmStaff",
                            NormalizedName = "FARMSTAFF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "86854584-fb05-4bfa-ae19-51dc71540f59",
                            RoleId = "9428f1f4-2c39-4fce-892c-85f349322fd0"
                        },
                        new
                        {
                            UserId = "b9ac39b7-df87-4572-a369-d1083a507b4e",
                            RoleId = "409901fa-62fc-4352-a873-b674d5140611"
                        },
                        new
                        {
                            UserId = "bc254da1-e0eb-4818-ab6f-90e7ece2eb07",
                            RoleId = "62a9c6e3-04be-4a4c-9a4a-1aa2a32d0c66"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Animal", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.Farm", "Farm")
                        .WithMany("Animals")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.AnimalHealthHistory", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.Animal", "Animal")
                        .WithMany("AnimalHealthHistories")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Animal_Health_System.DAL.Models.MedicalRecord", "MedicalRecord")
                        .WithMany()
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Appointment", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.Animal", "Animal")
                        .WithMany("Appointments")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Animal_Health_System.DAL.Models.Farm", "Farm")
                        .WithMany("Appointments")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Animal_Health_System.DAL.Models.FarmStaff", "FarmStaff")
                        .WithMany("Appointments")
                        .HasForeignKey("FarmStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Animal_Health_System.DAL.Models.Veterinarian", "Veterinarian")
                        .WithMany("Appointments")
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Farm");

                    b.Navigation("FarmStaff");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.AppointmentHistory", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.Appointment", "Appointment")
                        .WithMany("AppointmentHistories")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Birth", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.Animal", "Animal")
                        .WithMany("births")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animal_Health_System.DAL.Models.Pregnancy", "Pregnancy")
                        .WithMany("Births")
                        .HasForeignKey("PregnancyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Pregnancy");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Farm", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.Owner", "Owner")
                        .WithMany("Farms")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.FarmHealthSummary", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.Farm", "Farm")
                        .WithMany("FarmHealthSummaries")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.FarmStaff", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.Animal", null)
                        .WithMany("FarmStaffs")
                        .HasForeignKey("AnimalId");

                    b.HasOne("Animal_Health_System.DAL.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("FarmStaff")
                        .HasForeignKey("Animal_Health_System.DAL.Models.FarmStaff", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Animal_Health_System.DAL.Models.Farm", "Farm")
                        .WithMany("FarmStaffs")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Mating", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.Farm", "Farm")
                        .WithMany("Matings")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animal_Health_System.DAL.Models.Animal", "FemaleAnimal")
                        .WithMany()
                        .HasForeignKey("FemaleAnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Animal_Health_System.DAL.Models.Animal", "MaleAnimal")
                        .WithMany()
                        .HasForeignKey("MaleAnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("FemaleAnimal");

                    b.Navigation("MaleAnimal");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.MedicalExamination", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.Animal", "Animal")
                        .WithMany("MedicalExaminations")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Animal_Health_System.DAL.Models.MedicalRecord", "MedicalRecord")
                        .WithMany("Examinations")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animal_Health_System.DAL.Models.Veterinarian", "Veterinarian")
                        .WithMany("MedicalExaminations")
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("MedicalRecord");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.MedicalRecord", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.Animal", "Animal")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("Animal_Health_System.DAL.Models.MedicalRecord", "AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Notification", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.Animal", "Animal")
                        .WithMany("PregnancyNotifications")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Animal_Health_System.DAL.Models.FarmStaff", "FarmStaff")
                        .WithMany("Notifications")
                        .HasForeignKey("FarmStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Animal_Health_System.DAL.Models.Owner", "Owner")
                        .WithMany("Notifications")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Animal_Health_System.DAL.Models.Pregnancy", "Pregnancy")
                        .WithMany()
                        .HasForeignKey("PregnancyId");

                    b.HasOne("Animal_Health_System.DAL.Models.Veterinarian", "Veterinarian")
                        .WithMany("Notifications")
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Animal");

                    b.Navigation("FarmStaff");

                    b.Navigation("Owner");

                    b.Navigation("Pregnancy");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Owner", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Owner")
                        .HasForeignKey("Animal_Health_System.DAL.Models.Owner", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Pregnancy", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.Animal", "Animal")
                        .WithMany("Pregnancies")
                        .HasForeignKey("AnimalId");

                    b.HasOne("Animal_Health_System.DAL.Models.Mating", "Mating")
                        .WithMany("Pregnancies")
                        .HasForeignKey("MatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Mating");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.VaccineHistory", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.Vaccine", "vaccine")
                        .WithMany("VaccineHistories")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Animal_Health_System.DAL.Models.Veterinarian", "veterinarian")
                        .WithMany("VaccineHistories")
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Animal_Health_System.DAL.Models.MedicalRecord", "medicalRecord")
                        .WithMany("vaccineHistories")
                        .HasForeignKey("medicalRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("medicalRecord");

                    b.Navigation("vaccine");

                    b.Navigation("veterinarian");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Veterinarian", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Veterinarian")
                        .HasForeignKey("Animal_Health_System.DAL.Models.Veterinarian", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MedicalExaminationMedication", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.MedicalExamination", null)
                        .WithMany()
                        .HasForeignKey("MedicalExaminationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animal_Health_System.DAL.Models.Medication", null)
                        .WithMany()
                        .HasForeignKey("MedicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animal_Health_System.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Animal_Health_System.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Animal", b =>
                {
                    b.Navigation("AnimalHealthHistories");

                    b.Navigation("Appointments");

                    b.Navigation("FarmStaffs");

                    b.Navigation("MedicalExaminations");

                    b.Navigation("MedicalRecord")
                        .IsRequired();

                    b.Navigation("Pregnancies");

                    b.Navigation("PregnancyNotifications");

                    b.Navigation("births");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.ApplicationUser", b =>
                {
                    b.Navigation("FarmStaff");

                    b.Navigation("Owner");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentHistories");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Farm", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Appointments");

                    b.Navigation("FarmHealthSummaries");

                    b.Navigation("FarmStaffs");

                    b.Navigation("Matings");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.FarmStaff", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Mating", b =>
                {
                    b.Navigation("Pregnancies");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.MedicalRecord", b =>
                {
                    b.Navigation("Examinations");

                    b.Navigation("vaccineHistories");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Owner", b =>
                {
                    b.Navigation("Farms");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Pregnancy", b =>
                {
                    b.Navigation("Births");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Vaccine", b =>
                {
                    b.Navigation("VaccineHistories");
                });

            modelBuilder.Entity("Animal_Health_System.DAL.Models.Veterinarian", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalExaminations");

                    b.Navigation("Notifications");

                    b.Navigation("VaccineHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
